#Python Course I - class demo and homework assignments
- Google Classroom - Module 1 - 3

### Demo Topics
- input
- sting.upper, lower
- import - adding python modules/functions to memory
- date / time, formatting date ie: datetime.strptime
- random
- range
- for loop - loops for a fixed number of time
- if - expression to evaluate left and right variable and return true/false
- logical expressions, logical operatprs
- intro to array
- intro to list, set, tuple, map
    - set() - function is used to cast a list to set
    - list() - is used to cast a set to a list
    - tuple() - cas to list to tuple
    - dict() - cast a list to dictionary
- functions
- file input/output
- OOP classes
- python main startup module __name__ == "__main__"
- Other

#github course demos and examples

- https://github.com/deanliit/begin-adv-python-course-I

### HomeWork/Assignments

- Week 1-3

- Reading:

https://www.w3schools.com/python/python_intro.asp
- Variables, Data Type, Casting, Number, Operations

### Course book practices exercises  
- page 43, Exercise 1
- page 47, exercise 8
- page 48, exercise 10
- page 49, exercise 12




## Course I & II Module overview

<pre>
# Module 1
Python fundamentals
Data type
Variables
Input
for, while loop
Other

# Module 2
Array index
Slicers, list comprehension  
Functions
File input
Other

# Module 3
Data structures
Array, set, list, tuple, map
Classes
Lamda
Other

#optional - Module 4
Intro to data analyst using python
Pandas, numpy
SQL
Other

</pre>

### mathimatical expression or mathamital operations ()+,-%*^
<pre>
# ie math formulas - operations ()+,-%*^
#
#a = b + c
#a = b * c
#a = (b/2) + (c*3) .... etc..
#
#total = item1 + item2 + item3 + item4
</pre>

## Logical expression
<pre>
Expression to evaluate left and righ variable and return true or false
(), ==, <=, >=,
true/false = a == b
true/false = (a < b) or (a == b)
true/false = a and b or c > d or e = g
true/false = ((a and b) or (c > d) or (e == g))
other

</pre>

## Variable assignemt

a = fixed variable assignment - known value

a = dynamic variable assignmemt - ie: input
  - retrieve data from a file or database

python dynamicaly assigns a data type
- str, int, float, bool, other

cast from 1 data type to another

** more casting or converting from 1 datatype to another


some programming languages the variable data type is fixed or static
c/java, other

str a; //can only assign str to this variable

float b; //can only assign float to this variable

bool c;

int d;

** fast but doe resre a pre-compile step before running application



In [ ]:
#software development best practices - python, other

"""
#Refactoring: write code and mondify/enhance code ie: 1.0.0..1
#--------------------------------------
# systems/ program requirments
# ie: build the folloginw python program
# - researching python libraries, examples
# - demo code
# - more programs you write the more systems you can build
#--------------------------------------

-----------------------------------
Example Requirements
-----------------------------------

compute total of 3 items
prompt/input for name and price

example output:
name in upper case, current date and price

ITEM ONE    9/5/2024   100.5
ITEM TwO    9/5/2024    63.25
ITEM THREE  9/5/2024    12.3

total                 176.15

* round total
* item in upper case

--------------------------------------------
Development Best practice steps for many programs
--------------------------------------------
#1. import libraries
#2. get user input, files, database, web, other
#3. string data type
#4. cast string to other data type int, float, bool, other
#5. retrive system data and time
#6. retrieve day, month, year
#7. calculating total for 3 input items
#8. calculation or numerical expression
#9. rounding
#10. cast data from 1 type to another
#11. loop through a list of items
#12. varify if data is true/false ie: making a decision true/false
#13. output data - screen, file, database, web, other
# other

"""

In [ ]:
"""

==========================================================
Implent code using this weeks notebook topics
==========================================================

compute total of 5 items
prompt/input for name and price

example output:
name in upper case, current date and price

ITEM ONE    9/5/2024   100.5
ITEM TwO    9/5/2024    63.25
ITEM THREE  9/5/2024    12.3
ITEM FOUR   9/5/2024    132.13
ITEM FIVE   9/5/2024    102.23

total                  476.15

* round total
* item in upper case

"""

In [ ]:
#dict-demo-invoice-app-1.py

import datetime
import random

items = {} #dict()
date1 = datetime.datetime.now()
total = 0.0
TOTAL_ITEMS = 2

today1 = f"{date1.month}/{date1.day}/{date1.year}"

for i in range(TOTAL_ITEMS):
  price = random.randint(1,200)
  item = input(f"item-{(i+1)}: ")
  total = total + price
  items[item.upper()] = price

i = 0

for key in items:
  print(f"{key} - {today1} - {items[key]}")
  #i += 1

print("")
print("total: ", round(total,2))


In [ ]:
"""
### preview course book examples - intro to python examples ###

Functions
File input/output
Indexing slicing, slicers
list comprehension

"""

In [ ]:
#func-demo-1.py
#functions - name give to a group of 1 or more python code

#define function

def func1():
  pass

def func2():
  None

def func3():
  print("func3")

#call function
func1()
func3()



func3


In [ ]:
#func-demo-2.py

#pass 1 or more data to a function
#function prameter

def func4(item):
  print("func4 - ", item)

def func5(item1, item2):
  print("func5 - ", item1, item2)

#call function
func4("item one")
func5("item one", 123)



func4 -  item one
func5 -  item one 123


In [ ]:
#func-demo-3.py

#retrn data
def func5(item):
  ret = f"func5 - {item}"
  return ret

#return data
def func6(item1, item2):
  return (item1 + item2)

#call function
val1 = func5("item one")
val2 = func6(1,2)

print(val1)
print(val2)


func5 - item one
3


In [ ]:
##write-file-demo-1.py
## Save data to to file on disk
## -- example - write a function to save inventory item to file

#file is overwritten eact time code is ran
f = open("demo-1.txt", "w")

#create file if file does not exist and append to file if file exists
#f = open("demo-1.txt", "a")

f.write("introduction to file i/o" + "\n")
f.write("write data to file - demo 1" + "\n")
#f.writelines("write data to file - demo 1")
f.close()

print("demo-1.txt file created")

#display file in google colabs
#!ls
#!cat demo-1.txt


demo-1.txt file created


In [ ]:
#!ls
!ls
!cat demo-1.txt

demo-1.txt  sample_data
introduction to file i/o 
write data to file - demo 1 


In [ ]:
##read-file-demo-1.py
## read data from file on disk
## -- example - write a function to read inventory item from file

f = open("demo-1.txt", "r")
#read 1 line offile
print(f.read())
#print(f.readline())
f.close()

#display file in google colabs
#!ls


introduction to file i/owrite data to file - demo 1


In [ ]:
##read-file-demo-2.py
## read data from file on disk
## -- example - write a function to read inventory item from file

f = open("demo-1.txt", "r")

#read each file of file
for item in f:
  print(item)

#display file in google colabs
#!ls


introduction to file i/o

write data to file - demo 1



In [ ]:
#example code from course book - beginner chapter example
#page 43-44 - exercise 2
#word frequency counter
#word-frequency-counter-demo.py

"""
example demonstrates
- string
- dictionaries
- loop

"""

##
## Course book code exaples
## Beginner chapter code examples
##

"""

### Course book practices exercises
- page 43, Exercise 1
- page 47, exercise 8
- page 48, exercise 10
- page 49, exercise 12

............
page 43-44 - exercise 2
page 44 - exercise 3
page 44-45 - exercise 4
page 45 - exercise 5

"""


In [ ]:
## index slicing demo
#https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

list = [1,2,3,4]

#retrieving a range of items from array, list, set, tuple

#[from:to:step]
#ie: range (from:to:step)

## page 46, exercise 7


In [ ]:
#array index

#..................................................
#(positive) index start/top to end/bottom
#..................................................

#0=1
#1=2
#2=3

#...(positive index example).....horizontal....................

#0 1 2 3
#1 2 3 4

#..................................................
#(negative) index start/top to end/bottom
#..................................................
#-1 is always the end of the array, court backwards from -1, netavive value increase

#-3 or 0=1
#-2 or 1=2
#-1 or 2=3

#......(negative index example)..horizontal....................
#-1 is always the end of the array, court backwards from -1, netavive value increase

# 0   1   2   3
# 1   2   3   4
#-4  -3  -2  -1

#array, list, set, tuple
list1 = [1,2,3,4]

#example rage example (0,2)  start and 0 and stop before 2 ie: values 0-1  is accessed
#slicers and range always stop 1 before the end of ending number

#slicing syntax is similar to range
#step-by = optional, default = 1

# range example: (start,end,step-by-or-count-by)
# slicers example: [start:end:step-by-or-count-by]



In [2]:
#slicers-demo-1.py

list1 = [1,2,3,4,5,6,7]

#slicering, slicing arrya, retrieve a subset of data from array/list,set,tuple
#step-by = optional, default = 1

#positve index slicing
#start at 0 to 4 , not including 5, or stop before 5
print(list1[1:5])


[2, 3, 4, 5]


In [3]:
#slicers-demo-2.py
import numpy as np

#numpy - numeric or number/array library

#numpy - library used to generate sample arrays of small and large sizes, also manipulat arrays items (crud)
#- create, update and delete array items

#create array using numpy
list1 = np.array([1,2,3,4,5,6,7])

#slicering, slicing arrya, retrieve a subset of data from array/list,set,tuple
#step-by = optional, default = 1

#positve index slicing
#start at 0 to 4 , not including 5, or stop before 5
print(list1[1:5])


[2 3 4 5]


In [4]:
#slicers-demo-3.py
import numpy as np

list1 = np.array([1,2,3,4,5,6,7])

#start from index 4 - end at last index item
print(list1[4:])


[5 6 7]


In [8]:
#slicers-demo-3.py
import numpy as np

list1 = np.array([1,2,3,4,5,6,7])

#-- if index is out of rang, pthon stop at last index
#-- no out of bound error/exception
#print(list1[:10])

#start from index 0 , end/stop at index 4 or (4-1) or before index 4
print(list1[:4])



[1 2 3 4]


In [11]:
#slicers-demo-4.py
import numpy as np

list1 = np.array([1,2,3,4,5,6,7])

#from start to end of array ie: copy entire array
#print(list1[:])
#print(list1[::1])
#step by 2
print(list1[::2])

#from start to end of array ie: copy entire array
#step backword through array - reversing the array output
#print(list1[::-1])
#reverse array - step by 2
print(list1[::-2])


[1 3 5 7]
[7 5 3 1]


In [14]:
#slicers-demo-5.py
import numpy as np

#-7  -6  -5  -4  -3  -2  -1
#1    2   3   4   5   6   7

list1 = np.array([1,2,3,4,5,6,7])

#start at -3, stop 1 before end of the array
#print(list1[-3:-1])

#invalid start and end range
#print(list1[-1:-3])


[]


In [ ]:
## list comprehension
#https://www.w3schools.com/python/python_lists_comprehension.asp
## - 1 one stement - combining loop through list/set/tuple and also filtering list

#example loop and filter :
"""
- display odd number example

for i in range(10):
  if i % 2 == 0:
    print(i)


"""
## list comprehension example
##-- compnbine loop and filter in 1 stament
## in brackets
"""
[i for i in list i % 2 ]

#output befor for ... filter stament after list ...

"""

## page 46, exercise 6
